### PR TITLE
Update for 0.9 - WIP

### PR DESCRIPTION
**Pull request by cdata**

### CODE REVIEW

**Comment by cdata** [comment]
@addyosmani please give this a try when you have some time - I will be updating it over the course of the week.

**Comment by addyosmani** [comment]
We'll be rewriting the Reader app to use this port tomorrow. Will file feedback as we go along :)

**Comment by chuckh** [comment]
@cdata I have been testing this branch. The following does not seem to work:

1. order-by-child, no effect
2. equal-to, gives error  (Uncaught TypeError: this._stopListeningTo is not a function firebase-element:239)
3. equalTo, no effect
4. start-at, gives error (Uncaught TypeError: this._stopListeningTo is not a function firebase-element:239)
5. startAt, no effect

**Comment by cdata** [comment]
@chuckh awesome, thanks! I'll fix those issues.

**Pull request closed without merging**
