### PR TITLE
Rebuild for the new Polymer databinding paradigm.

### PR DESCRIPTION
**Pull request by cdata**
- Firebase Element has been split into Firebase Document and Firebase
   Collection.
 - Firebase Login has been renamed to Firebase Auth to match language in
   Firebase API.
 - Firebase Query Behavior is shared by Document and Collection, to
   support common patterns for attaching to locations and listening to
   API events.
 - A test suite has been created, although coverage is not complete.
   Notably, firebase-auth still has no test coverage.

### CODE REVIEW

**Comment by morethanreal** [comment]
lgtm. The refactoring makes sense to me and it's easier to understand than the single `firebase-element`.

**Comment by chuckh** [comment]
LGTM. Nice work @cdata! I look forward to trying it.

**Comment by addyosmani** [comment]
Changes LGTM. Nice work, @cdata!

**Comment by addyosmani** [comment]
@cdata following this, can we move the element over to GoogleWebComponents and tag a version that can be pulled in to the GWC element package before I/O?

**Comment by cdata** [comment]
Please go for it. I just tagged v0.9.0.

**Pull request merged**
